PlayasLimpiasWebApp/Controllers/EventController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using PlayasLimpiasWebApp.Models;
using PlayasLimpiasWebApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace PlayasLimpiasWebApp.Controllers
{
    public class EventController : Controller
    {
        //Service injection - database
        readonly IData db;

        //Required to get the user from Identity
        private readonly UserManager<User> UserManager;

        //Required to obtain the hosting enviroment
        private readonly IWebHostEnvironment _hostingEnv;

        public EventController(IData data, IWebHostEnvironment hostingEnv, UserManager<User> userManager)
        {
            db = data;
            _hostingEnv = hostingEnv;
            UserManager = userManager;
        }

        ////For Unit Testing Purposes
        //public EventController()
        //{
        //}

        //Index => All Events (UI)
        public IActionResult Index(string search)
        {
            try
            {
                //Check current user role
                if (HttpContext.User.IsInRole("Admin"))
                    ViewBag.Role = "Admin";
                else
                    ViewBag.Role = "User";
            }
            catch
            {
                //No exeption thrown; Users are allowed to view events without loggin in
            }

            EventCollectionViewModel ecvm = new EventCollectionViewModel();
            ecvm.EventCollection = db.GetAllEvents();

            if (String.IsNullOrWhiteSpace(search))
            {
                if (ecvm.EventCollection.Count == 0)
                    ViewBag.Message = "There are no events currentlly";

                return View("Index", ecvm);
            }

            //Filter events by search criteria
            ecvm.EventCollection = SearchResults(ecvm, search);

            if (ecvm.EventCollection.Count == 0)
                ViewBag.Message = "There are no events with that name currently";

            return View("Index", ecvm);
        }



        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult Create()
        {
            return View("Create");
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public async Task<IActionResult> Create(Event @event)
        {
            

            if (ModelState.IsValid) //confirms the form data is valid (server-side)
            {
                //Save event to database
                //Event needs to be sabe into the database first so that a id (PK) is generated
                db.AddEvent(@event);


                ViewBag.Message = await ImageProccessing(@event);

                //User that creates event is the first volunteer by default
                @event.NumVolunteers = 1;
                var userName = HttpContext.User.Identity.Name;
                User currentUser = await UserManager.FindByNameAsync(userName);
                db.VolunteerRelationship(@event, currentUser);

                db.UpdateEvent(@event);

                db.AddActivity(new Activity { Type = "Event Created", ActionBy = HttpContext.User.Identity.Name, AffectedEvent = @event.Name, ActionTimeStamp = DateTime.Now});
            }

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Event @event = db.GetEventById(id);
            return View(@event);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(Event @event)
        {
            Event oldEvent = db.GetEventById(@event.Id);

            //Additional Volunteers added by Administrator
            @event.NumVolunteers += oldEvent.NumVolunteers;

            if (ModelState.IsValid) //confirms the form data is valid
            {
                //If an new image has been uploaded, update event image
                if (@event.ImageFile != null && oldEvent.Image != @event.ImageFile.FileName)
                {
                    //Delete event old image from wwwroot
                    var path = Path.Combine(_hostingEnv.WebRootPath, "images", oldEvent.Image);
                    if (System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }

                    //Save new image
                    await ImageProccessing(@event);
                }

                db.UpdateEvent(@event);
                ViewBag.Message = "Event has been updated successfully!";

                db.AddActivity(new Activity { Type = "Event Edited", ActionBy = HttpContext.User.Identity.Name, AffectedEvent = @event.Name, ActionTimeStamp = DateTime.Now });
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]//Confirmation Page
        public IActionResult Delete(int id)
        {
            Event @event = db.GetEventById(id);

            if (@event == null)
                return NotFound();

            return View(@event);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Delete(Event @event)
        {
            //Get event image name
            string eventImageName = (db.GetEventById(@event.Id)).Image;

            //Delete event image from wwwroot
            var path = Path.Combine(_hostingEnv.WebRootPath, "images", eventImageName);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }


            db.RemoveEventRelationships(@event);
            db.RemoveEvent(@event.Id);

            db.AddActivity(new Activity { Type = "Event Deleted", ActionBy = HttpContext.User.Identity.Name, AffectedEvent = @event.Name, ActionTimeStamp = DateTime.Now });

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int id)
        {
            Event @event = db.GetEventById(id);

            if (@event == null)
                return NotFound();

            //Check if the user is already volunteering for this event
            var userName = HttpContext.User.Identity.Name;

            if(userName != null)
            {
                User currentUser = await UserManager.FindByNameAsync(userName);
                if (db.CheckRelationship(@event, currentUser))
                {
                    ViewBag.Message = "Exists";
                }

                //Check current user role
                if (HttpContext.User.IsInRole("Admin"))
                    ViewBag.Role = "Admin";
                else
                    ViewBag.Role = "User";
            }
            else
            {
                ViewBag.Message = "User not logged in";
            }

            return View(@event);
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> Volunteer(int id)
        {
            var userName = HttpContext.User.Identity.Name;
            User currentUser = await UserManager.FindByNameAsync(userName);

            Event @event = db.GetEventById(id);

            //Check if the user is already volunteering for this event
            if (db.CheckRelationship(@event, currentUser))
            {
                ViewBag.Message = "Exists";
            }
            else
            {
                db.VolunteerRelationship(@event, currentUser);
                ViewBag.Message = "Success";
                @event.NumVolunteers++;
                db.UpdateEvent(@event);

                db.AddActivity(new Activity { Type = "User Volunteered", ActionBy = HttpContext.User.Identity.Name, AffectedEvent = @event.Name, ActionTimeStamp = DateTime.Now });
            }
            
            return View("Details", @event);
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> Unvolunteer(int id)
        {
            var userName = HttpContext.User.Identity.Name;
            User currentUser = await UserManager.FindByNameAsync(userName);

            Event @event = db.GetEventById(id);

            db.Unvolunteer(@event, currentUser);
            @event.NumVolunteers--;
            db.UpdateEvent(@event);

            db.AddActivity(new Activity { Type = "User Unvolunteered", ActionBy = HttpContext.User.Identity.Name, AffectedEvent = @event.Name, ActionTimeStamp = DateTime.Now });

            return RedirectToAction("MyEvents");
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> MyEvents(string search)
        {
            EventCollectionViewModel ecvm = new EventCollectionViewModel();

            //Get user
            var userName = HttpContext.User.Identity.Name;
            User currentUser = await UserManager.FindByNameAsync(userName);

            ecvm.EventCollection = db.GetMyEvents(currentUser);

            if (String.IsNullOrWhiteSpace(search))
            {
                if (ecvm.EventCollection.Count == 0)
                    ViewBag.Message = "You do not have any events, check out all the ongoing events below";
                return View(ecvm);
            }

            //Filter events by search criteria
            ecvm.EventCollection = SearchResults(ecvm, search);

            if (ecvm.EventCollection.Count == 0)
                ViewBag.Message = "There are no events with that name in your list";

            return View(ecvm);
        }

        //Filter events by search criteria
        //Private method, internally use, encapsulation; make public only for testing purposes 
        public List<Event> SearchResults(EventCollectionViewModel ecvm, string search)
        {
            search = search.ToLower();
            List<Event> searchResults = new List<Event>();

PlayasLimpiasWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PlayasLimpiasWebApp.Models;
using PlayasLimpiasWebApp.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PlayasLimpiasWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        IData db;

        public HomeController(ILogger<HomeController> logger, IData _data)
        {
            _logger = logger;
            db = _data;
        }

        public IActionResult Index()
        {
            return View("Index");
        }

        public IActionResult Privacy()
        {
            return View("Privacy");
        }

        public IActionResult About()
        {
            return View("About");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return base.View(new ErrorViewModel { RequestId = System.Diagnostics.Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PlayasLimpiasWebApp/Controllers/ReportController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlayasLimpiasWebApp.Models;
using PlayasLimpiasWebApp.Services;
using PlayasLimpiasWebApp.ViewModels;
using System;
using System.Collections.Generic;

namespace PlayasLimpiasWebApp.Controllers
{
    public class ReportController : Controller
    {
        IData db;

        public ReportController(IData data)
        {
            db = data;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult ActivityReport()
        {
            ActivityCollectionViewModel report = new ActivityCollectionViewModel();
            report.ActivityCollection = db.GetAllActivity();

            return View(report);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult VolunteeringReport()
        {
            int activeVolunteers = 0;
            List<Event> lessThan50percentage = new List<Event>();

            foreach(var e in db.GetAllEvents())
            {
                activeVolunteers += e.NumVolunteers;

                if(e.NumVolunteers < (e.NumVolunteersReq/2))
                    lessThan50percentage.Add(e);
            }

            VolunteeringReportViewModel report = new VolunteeringReportViewModel
            {
                TimeStamp = DateTime.Now.ToString("f"),
                NumActiveUsers = db.GetAllUsers().Count,
                NumActiveEvents = db.GetAllEvents().Count,
                NumActiveVolunteers = activeVolunteers,
                LessThan50PerOfVolunteers = lessThan50percentage,
                VolunteeringPercentage = (int)((activeVolunteers/db.GetAllUsers().Count)*100)

            };


            return View(report);
        }
    }
}

PlayasLimpiasWebApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<h1 class="display-1 d-flex justify-content-center" style="color: seashell;">About</h1>


<div class="card mb-3 text-bg-dark">
  <div class="row g-0">
    <div class="col-md-4">
      <div id="carouselExampleInterval" class="carousel slide carousel-fade" data-bs-ride="carousel" style="margin:15px;">
      <div class="carousel-inner">
        <div class="carousel-item" data-bs-interval="4000">
          <img src="~/images/aboutImg (2).jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item" data-bs-interval="4000">
          <img src="~/images/aboutImg (3).jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item" data-bs-interval="4000">
          <img src="~/images/aboutImg (4).jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item active" data-bs-interval="4000">
          <img src="~/images/aboutImg (5).jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item" data-bs-interval="4000">
          <img src="~/images/aboutImg (6).jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item" data-bs-interval="4000">
          <img src="~/images/aboutImg (7).jpg" class="d-block w-100" alt="...">
        </div>
      </div>
    </div>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">We are a Community</h5>
        <p class="card-text">
            The island of Puerto Rico has many of the most beautiful coast lines in the world, 
            consequently these coast lines received high volume of visitors throughout the year, 
            even higher on holidays. Many of the visitors bring multiple food, drinks, and many other items that contain 
            packaging plastics and other materials. Sadly, it has become an increasing problem that many of the visitors 
            leave these items behind contaminating the beautiful coastlines and posing risks to many maritime animals.
            <h5>It's our duty to protect our coastlines</h5>
            Every year millions of pounds of trash are left at beaches by both 
            locals and tourists. When all this trash stays behind in the shorelines it can be dragged into the ocean putting 
            many more ecosystems at risk. 
            <br/>
            <figure>
            <blockquote class="blockquote">
                <p>‘’Marine litter is not only ugly – it can harm ocean ecosystems, wildlife, and humans. 
                    It can injure coral reefs and bottom-dwelling species and entangle or drown ocean wildlife. 
                    Some marine animals ingest smaller plastic particles and choke or starve”
                </p>
            </blockquote>
            <figcaption class="blockquote-footer">
                marinelittersolutions.com in <cite title="Source Title">What is marine debris? 2020</cite>
            </figcaption>
            </figure>
            Many individuals will gladly volunteer their time and help clean our coastlines, but to make a significant impact, many volunteers is often needed. 
            Many non-profit organizations perform coast rescue events (trash clean up), however they mostly do on an annual basis, which is not enough to fight 
            the pollution on our coastlines, and that when we come in.
            <br />
            <h5>Playas Limpias</h5>
            As a non-profit organization we provide this platform to allow anyone with the intention to raise volunteer and protect our coatslines.
        </p>
        <p class="card-text"><a class="btn btn-sm btn-outline-warning" asp-action="Index" asp-controller="Event">View Events</a></></p>
      </div>
    </div>
  </div>
</div >
<p><strong>More information at <abbr title="Departamento de Recursos Naturales y Ambientales">DRNA</abbr></strong></p>
<div style="margin-top:50px; margin-bottom:100px; display:inline-flex">
    <div style="margin:5px;"><a class="btn btn-sm btn-warning" href="https://www.drna.pr.gov/"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-globe" viewBox="0 0 16 16">
      <path d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm7.5-6.923c-.67.204-1.335.82-1.887 1.855A7.97 7.97 0 0 0 5.145 4H7.5V1.077zM4.09 4a9.267 9.267 0 0 1 .64-1.539 6.7 6.7 0 0 1 .597-.933A7.025 7.025 0 0 0 2.255 4H4.09zm-.582 3.5c.03-.877.138-1.718.312-2.5H1.674a6.958 6.958 0 0 0-.656 2.5h2.49zM4.847 5a12.5 12.5 0 0 0-.338 2.5H7.5V5H4.847zM8.5 5v2.5h2.99a12.495 12.495 0 0 0-.337-2.5H8.5zM4.51 8.5a12.5 12.5 0 0 0 .337 2.5H7.5V8.5H4.51zm3.99 0V11h2.653c.187-.765.306-1.608.338-2.5H8.5zM5.145 12c.138.386.295.744.468 1.068.552 1.035 1.218 1.65 1.887 1.855V12H5.145zm.182 2.472a6.696 6.696 0 0 1-.597-.933A9.268 9.268 0 0 1 4.09 12H2.255a7.024 7.024 0 0 0 3.072 2.472zM3.82 11a13.652 13.652 0 0 1-.312-2.5h-2.49c.062.89.291 1.733.656 2.5H3.82zm6.853 3.472A7.024 7.024 0 0 0 13.745 12H11.91a9.27 9.27 0 0 1-.64 1.539 6.688 6.688 0 0 1-.597.933zM8.5 12v2.923c.67-.204 1.335-.82 1.887-1.855.173-.324.33-.682.468-1.068H8.5zm3.68-1h2.146c.365-.767.594-1.61.656-2.5h-2.49a13.65 13.65 0 0 1-.312 2.5zm2.802-3.5a6.959 6.959 0 0 0-.656-2.5H12.18c.174.782.282 1.623.312 2.5h2.49zM11.27 2.461c.247.464.462.98.64 1.539h1.835a7.024 7.024 0 0 0-3.072-2.472c.218.284.418.598.597.933zM10.855 4a7.966 7.966 0 0 0-.468-1.068C9.835 1.897 9.17 1.282 8.5 1.077V4h2.355z"/>
    </svg></a></div>
    <div style="margin:5px;"><a class="btn btn-sm btn-warning" href="https://www.facebook.com/drnapr/"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
      <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
    </svg></a></div>
    <div style="margin:5px;"><a class="btn btn-sm btn-warning" href="https://twitter.com/DRNAPR"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
      <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
    </svg></a></div>
</div>

PlayasLimpiasWebApp/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Playas Limpias</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="font-family:noto">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3 onTop" >
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/NavBarLogo.png" width="200"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Events</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" asp-controller="Event" asp-action="Index">All Events</a></li>
                                <li><a class="dropdown-item" asp-controller="Event" asp-action="MyEvents">My Events</a></li>
                                <li><a class="dropdown-item" asp-controller="Event" asp-action="Create">Create an Event</a></li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>

                    </ul>

                     <div class="col-4 d-flex justify-content-end align-items-center">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <strong>@User.Identity.Name</strong>
                            <a class="btn btn-sm btn-outline-secondary" style="margin-left:10px;" asp-controller="Account" asp-action="Logout">Logout</a>
                            @if (User.IsInRole("Admin"))
                            {
                                <ul class="navbar-nav flex-grow-1" style="margin-left:10px;">
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Reports</a>
                                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                            <li><a class="dropdown-item" asp-controller="Report" asp-action="ActivityReport">Activity Report</a></li>
                                            <li><a class="dropdown-item" asp-controller="Report" asp-action="VolunteeringReport">Volunteering Report</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            }
                        }
                        else
                        {
                            <a class="btn btn-sm btn-outline-secondary" asp-controller="Account" asp-action="Login">Login</a>
                            <a class="btn btn-sm btn-outline-secondary" style="margin-left:10px;" asp-controller="Account" asp-action="Register">Register</a>
                        }
                    </div>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            

            @{
                ViewData["Title"] = "Home Page";
            }

            <div class="text-center landingPage">


                <video muted loop autoplay>
                    <source src="~/videos/homeBackgroung.mp4" type="video/mp4"/>
                </video>

                <img class="img-fluid homeLogoImg" src="~/images/HomeLogo1.png"/>


                <div class="options">
                    <a class="btn btn-sm btn-outline-warning btn-lg" style="margin:20px" asp-action="Index" asp-controller="Event"><h4>Explore Events - Volunteer</h4></a>
                    <a class="btn btn-sm btn-outline-warning btn-lg" style="margin:20px" asp-action="Create" asp-controller="Event"><h4>Rescue a Coastline - Create an Event</h4></a>
                </div>
    

            </div>

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Playas Limpias - Video by Jess Loiterton <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>